name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: anket-cd/shared-workflows/.github/workflows/pr_checks.yml@master # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
