name: PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: anket-cd/shared-workflows/.github/workflows/pr-checks.yml@4d02cf319a3e01577012a5a58fbe31266923df1d # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
